//main
const main = [
    { english: 'My Files', serbian: 'Moji Fajlovi' },
    { english: 'Name', serbian: 'Ime' },
    { english: 'Size', serbian: 'Veličina' },
    { english: 'Modified', serbian: 'Modifikovano' },
    { english: 'Open in new Tab', serbian: 'Otovori u novoj kartici' },
    { english: 'Preview', serbian: 'Pregledaj' },
    { english: 'Open With', serbian: 'Otvori Pomoću' },
    { english: 'Open Folder', serbian: 'Otvori Folder' },
    { english: 'Share Link', serbian: 'Podeli Link' },
    { english: 'Add to Favorites', serbian: 'Dodaj u Označene' },
    { english: 'Remove from Favorites', serbian: 'Skloni iz Označenih' },
    { english: 'Rename', serbian: 'Preimenuj' },
    { english: 'View Informations', serbian: 'Pogledaj Informacije' },
    { english: 'Make a copy', serbian: 'Napravi Kopiju' },
    { english: 'Download', serbian: 'Preuzmi' },
    { english: 'Remove', serbian: 'Obriši' },
    { english: 'Create Folder', serbian: 'Napravi Folder' },
    { english: 'Create File', serbian: 'Napravi Fajl' },
    { english: 'Upload File', serbian: 'Otpremi Fajl' },
    { english: 'File Information', serbian: 'Informacije o Fajlu' },
    { english: 'Upload Files', serbian: 'Otpremi Fajlove' },
]
//nav
const nav = [
    { english: 'Add New', serbian: 'Novo' },
    { english: 'Create Folder', serbian: 'Napravi Folder' },
    { english: 'Upload Folder', serbian: 'Otpremi Folder' },
    { english: 'Upload File', serbian: 'Otpremi Fajl' },
    { english: 'My Photos', serbian: 'Moje Slike' },
    { english: 'Upgrade PLAN', serbian: 'Nadogradi PLAN' },
    { english: 'My Files', serbian: 'Moji Fajlovi' },
    { english: 'Shared With Me', serbian: 'Podeljeno Samnom' },
    { english: 'Favorites', serbian: 'Sa Zvezdicom' },
    { english: 'Trashed Files', serbian: 'Obrisani Fajlovi' },
    { english: 'Cancel', serbian: 'Otkaži' },
    { english: 'Share With Others', serbian: 'Podeli Sa Ostalima'},
    { english: 'Enter user Email', serbian: 'Unesi email korisnika' },
    { english: 'Save', serbian: 'Sačuvaj' },
    { english: 'Affiliate', serbian: 'Udružimo se' },
    { english: 'Search Drive', serbian: 'Pretraži Drajv' },
    { english: 'Switch Accounts', serbian: 'Promeni Nalog' },
    { english: 'Account Settings', serbian: 'Podešavanja Naloga' },
    { english: 'Help & Support', serbian: 'Pomoć & Podrška' },
    { english: 'Theme & Language', serbian: 'Tema & Jezik' },
    { english: 'Logout', serbian: 'Odjavi se' },
    { english: 'Switch Accounts', serbian: 'Promeni Nalog' },
    { english: 'Settings & Security', serbian: 'Podešavanja & Bezbednost' },
    { english: '2F Authentication', serbian: 'Autentikacija sa 2Faktora' },
    { english: 'Account Settings', serbian: 'Podešavanje Naloga' },
    { english: 'Privacy Settings', serbian: 'Podešavanja Privatnosti' },
    { english: 'Activity List', serbian: 'Lista Aktivnosti' },
    { english: 'Help & Support', serbian: 'Pomoć i Podrška' },
    { english: 'Ask Question', serbian: 'Postavi Pitanje' },
    { english: 'Report a Problem', serbian: 'Prijavi Problem' },
    { english: 'Select Language', serbian: 'Izaberi Jezik' },
    { english: 'English', serbian: 'Engleski' },
    { english: 'Russian', serbian: 'Ruski' },
    { english: 'Serbian', serbian: 'Srpski' },
    { english: 'Theme & Language', serbian: 'Tema & Jezik' },
    { english: 'Dark Mode', serbian: 'Temna Tema' },
    { english: 'Choose Between Dark and Light mode, or let it automatically sync with device.', serbian: 'Odaberite izmedju tamnog i svetlog moda, ili da se automatski sinhronizuje sa vašim uredjajem.' },
    { english: 'Off', serbian: 'Isključen' },
    { english: 'On', serbian: 'Uključen' },
    { english: 'Device Theme', serbian: 'Tema Uredjaja' },
    { english: 'Languages', serbian: 'Jezici' },
    { english: 'Revoke', serbian: 'Opozvati' },
    { english: 'Keyboard Shortcuts', serbian: 'Tasterske Prečice' },
    { english: 'Select multiple files', serbian: 'Izaberi više fajlova' },
    { english: 'Select files between', serbian: 'Izaberite fajlove izmedju' },
    { english: 'Open file - Go in', serbian: 'Otvori fajl ili folder' },
    { english: 'Select next file', serbian: 'Izaberi sledeći fajl' },
    { english: 'Select previous file', serbian: 'Izaberi prethodni fajl' },
    { english: 'Delete all selected', serbian: 'Obriši sve izabrano' },
    { english: 'Show file info', serbian: 'Prikaži opis fajla' },
    { english: 'Create directory', serbian: 'Napravi novi folder' },
    { english: 'Go to previous directory', serbian: 'Idi na prethodni folder' },
    { english: 'Refresh directory', serbian: 'Osveži trenutni folder' },
    { english: 'Copy selected files', serbian: 'Kopiraj izabrano' },
    { english: 'Undo previous move', serbian: 'Opozovi prethodni korak' },
    { english: 'Keyboard shortcuts', serbian: 'Tasterske prečice' },
    { english: 'Close', serbian: 'Zatvori' },
    { english: 'Selecting', serbian: 'Biranje' },
    { english: 'Interaction', serbian: 'Interakcije' },
    { english: 'Additional', serbian: 'Dodatno' },
    { english: 'Home', serbian: 'Početna' },
    { english: 'Personal Data', serbian: 'Lični Podaci' },
    { english: 'Security', serbian: 'Bezbednost' },
]
module.exports = scripts = (doc ,language) => {
    const resp = [];
    if(doc == 'nav') {
        if(language == 'serbian') nav.forEach(script => { resp.push(script.serbian) });
        else nav.forEach(script => { resp.push(script.english) });
    }else if(doc == 'main') {
        if(language == 'serbian') main.forEach(script => { resp.push(script.serbian) });
        else main.forEach(script => { resp.push(script.english) });
    }
    return resp;
}